# 워크플로우의 이름
name: Deploy to AWS EC2 with Git Pull

# 실행 조건: 'main' 브랜치에 push 이벤트가 발생했을 때만 실행
on:
  push:
    branches:
      - main

# 실행될 작업(Job) 정의
jobs:
  deploy:
    # 이 작업이 실행될 가상 환경의 종류
    runs-on: ubuntu-latest

    # 작업의 단계(Step)들
    steps:
      # 1. EC2 서버에 접속하여 배포 스크립트 실행 (SSH)
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: | # EC2 서버에서 순차적으로 실행될 명령어들
            # 1. 프로젝트 폴더로 이동
            cd ~/LoaPlan
            
            # 2. git pull을 통해 최신 소스 코드를 받아옴
            git pull origin main
            
            # 3. Client 측 의존성 설치 및 프로덕션 빌드
            echo "Building Client..."
            cd Client
            npm ci
            npm run build
            
            # 4. Server 측 의존성 설치 (배포에 필요한 것만)
            echo "Installing Server Dependencies..."
            cd ../Server
            npm ci --production
            
            # 5. PM2를 이용하여 서버를 중단 없이 재시작
            echo "Reloading PM2 Server..."
            pm2 reload loaplan-server
